{{- if or .Values.daemonset.deploy .Values.delegatedAgentDeployment.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent.configmapName" . }}
  namespace: {{ include "agent.namespace" . }}
  labels:
{{ (include "agent.labels" .) | indent 4 }}
data:
  dragent.yaml: |
    new_k8s: true
{{- include "agent.clusterName" . | trim | nindent 4 }}
{{- if .Values.delegatedAgentDeployment.enabled }}
    cointerface_enabled: false
{{- end }}
{{- include "agent.connectionSettings" . | trim | nindent 4 }}
{{- include "agent.planSettings" . | trim | nindent 4 }}
{{- include "agent.k8sColdStart" . | nindent 4 }}
{{- include "agent.disableCaptures" . | nindent 4 }}
{{- include "agent.logSettings" . }}
{{- if .Values.global.sysdig.tags }}
    tags: {{ include "agent.tags" . }}
{{- end }}
{{/*
  Checking here the user is using Custom CA and if http_proxy.ssl = true
  If these conditions are true, then we use the agent.sslCaFileName for the http_proxy.ca_certificate
*/}}
{{- if and (include "agent.printCA" .) (.Values.sysdig.settings) (hasKey .Values.sysdig.settings "http_proxy") (hasKey .Values.sysdig.settings.http_proxy "ssl") (eq (get .Values.sysdig.settings.http_proxy "ssl") true) }}
  {{- $baseSettings := .Values.sysdig.settings -}}
  {{- $caFileName := include "agent.sslCaFileName" . }}
  {{- $caFilePath := printf "%s%s" "/ca-certs/" $caFileName }}
  {{- $mergedSettings := mergeOverwrite $baseSettings (dict "http_proxy" (dict "ca_certificate" $caFilePath)) -}}
  {{ toYaml $mergedSettings | indent 4 }}
{{- else if .Values.sysdig.settings }}
  {{ toYaml .Values.sysdig.settings | indent 4 }}
{{- end }}
{{- if .Values.leaderelection.enable }}
    k8s_delegation_election: true
    k8s_coldstart:
      enabled: true
      enforce_leader_election: true
      namespace: {{ include "agent.namespace" . }}
{{- end }}
{{- if .Values.global.sysdig.tags }}
    tags: {{ include "agent.tags" . }}
{{- end }}
{{- if .Values.prometheus.file }}
  prometheus.yaml: |
{{ toYaml .Values.prometheus.yaml | indent 4 }}
{{- end }}
{{- end }}
