{{- if not ( include "agent.accessKeySecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "agent.fullname" . }}
  namespace: {{ include "agent.namespace" . }}
  labels:
{{ include "agent.labels" . | indent 4 }}
type: Opaque
data:
 access-key : {{ include "agent.accessKey" . | b64enc | quote }}
---
{{- end }}
{{- range .Values.extraSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ include "agent.namespace" $ }}
  labels:
{{ include "agent.labels" $ | indent 4 }}
type: Opaque
data:
{{ toYaml .data | indent 2 }}
---
{{- end }}
{{- if .Values.ssl.ca.cert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" . }}-ca
  namespace: {{ include "agent.namespace" . }}
  labels:
{{ include "agent.labels" . | indent 4 }}
data:
  {{ include "agent.sslCaFileName" .}}: {{ include "agent.printCA" . | b64enc | quote }}
---
{{- end }}
