{{- if not ( include "kspmCollector.accessKeySecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kspmCollector.fullname" . }}
  namespace: {{ include "kspmCollector.namespace" . }}
  labels:
{{ include "kspmCollector.labels" . | indent 4 }}
type: Opaque
data:
 access-key : {{ include "kspmCollector.accessKey" . | b64enc | quote }}
---
{{- end }}
{{- if .Values.ssl.ca.cert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kspmCollector.fullname" . }}-ca
  namespace: {{ include "kspmCollector.namespace" . }}
  labels:
{{ include "kspmCollector.labels" . | indent 4 }}
data:
  {{ include "kspmCollector.sslCaFileName" .}}: {{ include "kspmCollector.printCA" . | b64enc | quote }}
---
{{- end }}
